# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BibleGuardian' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BibleGuardian
  pod 'Moya', '~> 12.0.1'
  pod 'SnapKit', '~> 4.2.0'
#  pod 'Socket.IO-Client-Swift', '~> 13.4.0'
end
